name: Build_and_deploy_action
#on:
#  push:
#    branches:
#      - master

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v4
      - name: docker build app
        run: docker build -t alexeygalt/enc_bot:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push app
        run: docker push alexeygalt/enc_bot:$GITHUB_REF_NAME-$GITHUB_RUN_ID


  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    timeout-minutes: 30
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_IDS: ${{ secrets.CHATS_ID }}

    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: render config
        run: |
          mkdir deploy
          
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
          cat .docker_env-ci | envsubst > deploy/.env


      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "deploy/docker-compose.yaml,deploy/.env"
          target: "app"
          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd app
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose up -d
#          script: |
#            cd app
#            for i in {1..5}; do
#              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose up -d && break || echo "Attempt $i failed! Trying again in 5 seconds..." && sleep 5;
#            done

#tes